package dnsfallback

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestEnsureMissingFile(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "resolv.conf")

	action, err := Ensure(path, DefaultNameservers)
	if err != nil {
		t.Fatalf("Ensure: %v", err)
	}
	if action != ActionWrote {
		t.Fatalf("action = %v, want ActionWrote", action)
	}
	body, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	got := string(body)
	if !strings.Contains(got, "nameserver 1.1.1.1") {
		t.Fatalf("missing 1.1.1.1: %s", got)
	}
	if !strings.Contains(got, "nameserver 9.9.9.9") {
		t.Fatalf("missing 9.9.9.9: %s", got)
	}
}

func TestEnsureEmptyFile(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "resolv.conf")
	if err := os.WriteFile(path, []byte(""), 0o644); err != nil {
		t.Fatal(err)
	}
	action, err := Ensure(path, []string{"8.8.8.8"})
	if err != nil {
		t.Fatalf("Ensure: %v", err)
	}
	if action != ActionWrote {
		t.Fatalf("action = %v, want ActionWrote", action)
	}
	body, _ := os.ReadFile(path)
	if !strings.Contains(string(body), "nameserver 8.8.8.8") {
		t.Fatalf("body missing 8.8.8.8: %s", body)
	}
}

func TestEnsureCommentsOnly(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "resolv.conf")
	if err := os.WriteFile(path, []byte("# generated by something\n# nothing here\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	action, err := Ensure(path, DefaultNameservers)
	if err != nil {
		t.Fatalf("Ensure: %v", err)
	}
	if action != ActionWrote {
		t.Fatalf("action = %v, want ActionWrote", action)
	}
}

func TestEnsureExistingNameserverPreserved(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "resolv.conf")
	original := "search example.com\nnameserver 192.168.1.1\noptions edns0\n"
	if err := os.WriteFile(path, []byte(original), 0o644); err != nil {
		t.Fatal(err)
	}
	action, err := Ensure(path, DefaultNameservers)
	if err != nil {
		t.Fatalf("Ensure: %v", err)
	}
	if action != ActionUnchanged {
		t.Fatalf("action = %v, want ActionUnchanged", action)
	}
	body, _ := os.ReadFile(path)
	if string(body) != original {
		t.Fatalf("file modified: got %q want %q", body, original)
	}
}

func TestEnsureNameserverWithoutValueNotEnough(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "resolv.conf")
	// A bare "nameserver" with no value should not count as configured.
	if err := os.WriteFile(path, []byte("nameserver\n# foo\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	action, err := Ensure(path, DefaultNameservers)
	if err != nil {
		t.Fatalf("Ensure: %v", err)
	}
	if action != ActionWrote {
		t.Fatalf("action = %v, want ActionWrote", action)
	}
}

func TestEnsureRejectsEmptyArgs(t *testing.T) {
	if _, err := Ensure("", DefaultNameservers); err == nil {
		t.Fatalf("expected error for empty path")
	}
	if _, err := Ensure("/tmp/x", nil); err == nil {
		t.Fatalf("expected error for empty nameservers")
	}
}

func TestEnsurePropagatesReadErrors(t *testing.T) {
	dir := t.TempDir()
	// A directory at the path will cause ReadFile to return EISDIR,
	// which is neither nil nor ErrNotExist — Ensure must surface it.
	path := filepath.Join(dir, "resolv.conf")
	if err := os.MkdirAll(path, 0o755); err != nil {
		t.Fatal(err)
	}
	if _, err := Ensure(path, DefaultNameservers); err == nil {
		t.Fatalf("expected error when path is a directory")
	}
}
